if(Boost_DEBUG)
    message(STATUS "Boost debug mode is active")
    find_package(Boost 1.79.0 REQUIRED COMPONENTS ALL)
else()
    find_package(Boost 1.79.0 REQUIRED COMPONENTS program_options json)
endif()
